if(NOT DEFINED GLTF_FIXTURE OR NOT DEFINED OUTPUT_DIR)
  message(FATAL_ERROR "GLTF_FIXTURE and OUTPUT_DIR are required")
endif()

file(MAKE_DIRECTORY "${OUTPUT_DIR}")
set(first "${OUTPUT_DIR}/first.glb")
set(second "${OUTPUT_DIR}/second.glb")
execute_process(COMMAND "${GLTF_FIXTURE}" "${first}" RESULT_VARIABLE first_result)
execute_process(COMMAND "${GLTF_FIXTURE}" "${second}" RESULT_VARIABLE second_result)
if(NOT first_result EQUAL 0 OR NOT second_result EQUAL 0)
  message(FATAL_ERROR "fresh-process GLB fixture failed")
endif()
file(SHA256 "${first}" first_hash)
file(SHA256 "${second}" second_hash)
if(NOT first_hash STREQUAL second_hash)
  message(FATAL_ERROR "fresh processes emitted different GLB bytes: ${first_hash} != ${second_hash}")
endif()
file(REMOVE "${first}" "${second}")
