#!/usr/bin/env python3
"""Generate compact C++ schema tables from reviewed neutral manifests."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


TYPE_NAMES = {
    0: "FieldType::u32",
    1: "FieldType::f32",
    2: "FieldType::f64",
    3: "FieldType::text",
    4: "FieldType::bytes",
}


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def descriptors(table: dict) -> tuple[int, ...]:
    return (
        table["record_identity_descriptor"],
        *(field["descriptor"] for field in table.get("fields", [])),
    )


def has_native_layout(table: dict) -> bool:
    fields = table.get("fields", [])
    return bool(fields) and all(
        isinstance(field.get("name"), str)
        and field.get("type_code") in TYPE_NAMES
        and isinstance(field.get("byte_offset"), int)
        and isinstance(field.get("byte_size"), int)
        for field in fields
    )


def signature(table: dict) -> tuple:
    return table["name"], table["tuple_size"], descriptors(table)


def generate(manifests: list[dict]) -> str:
    native_tables = {
        signature(table): table
        for manifest in manifests
        for table in manifest["tables"]
        if has_native_layout(table)
    }
    descriptor_pool: list[int] = []
    descriptor_offsets: dict[tuple[int, ...], int] = {}
    field_pool: list[dict] = []
    field_offsets: dict[tuple[tuple, ...], int] = {}
    table_rows_by_token: dict[str, list[str]] = {}
    schema_names: list[str] = []

    for manifest in manifests:
        token = manifest["internal_format"].replace(".", "_")
        schema_names.append(token)
        table_rows: list[str] = []
        for table in manifest["tables"]:
            table_descriptors = descriptors(table)
            if table_descriptors not in descriptor_offsets:
                descriptor_offsets[table_descriptors] = len(descriptor_pool)
                descriptor_pool.extend(table_descriptors)
            descriptor_offset = descriptor_offsets[table_descriptors]

            native = table if has_native_layout(table) else native_tables.get(signature(table))
            fields = native.get("fields", []) if native is not None else []
            if not has_native_layout({"fields": fields}):
                fields = []
            field_key = tuple(
                (
                    field["name"],
                    field["type_code"],
                    field["byte_offset"],
                    field["byte_size"],
                )
                for field in fields
            )
            if field_key not in field_offsets:
                field_offsets[field_key] = len(field_pool)
                field_pool.extend(fields)
            field_offset = field_offsets[field_key]

            table_key = table.get("table_key")
            table_rows.append(
                "  TableSchema{%d, %s, %d, %s, %d, %d, %d, %d, %d},"
                % (
                    table["ordinal"],
                    cpp_string(table["name"]),
                    table["tuple_size"],
                    "true" if table_key is not None else "false",
                    table_key or 0,
                    descriptor_offset,
                    len(table_descriptors),
                    field_offset,
                    len(fields),
                )
            )
        table_rows_by_token[token] = table_rows

    lines = [
        '// Generated by codegen/generate_schemas.py. Do not edit.',
        '#include "../schema.hpp"',
        '',
        '#include <array>',
        '',
        'namespace tekla::db1::detail {',
        'namespace {',
        '',
    ]

    lines.append(
        f"constexpr std::array<std::uint8_t, {len(descriptor_pool)}> descriptors{{{{"
    )
    for offset in range(0, len(descriptor_pool), 32):
        lines.append("  " + ", ".join(map(str, descriptor_pool[offset : offset + 32])) + ",")
    lines.append("}};")
    lines.append("")

    lines.append(f"constexpr std::array<FieldSchema, {len(field_pool)}> fields{{{{")
    for field in field_pool:
        lines.append(
            "  FieldSchema{%s, %s, %d, %d},"
            % (
                cpp_string(field["name"]),
                TYPE_NAMES[field["type_code"]],
                field["byte_offset"],
                field["byte_size"],
            )
        )
    lines.append("}};")
    lines.append("")

    for manifest in manifests:
        token = manifest["internal_format"].replace(".", "_")
        lines.append(
            f"constexpr std::array<TableSchema, {len(table_rows_by_token[token])}> "
            f"tables_{token}{{{{"
        )
        lines.extend(table_rows_by_token[token])
        lines.append("}};")
        lines.append("")
        lines.append(
            f"constexpr Schema schema_{token}{{{cpp_string(manifest['internal_format'])}, "
            f"{manifest['database_kind_marker']}, tables_{token}, descriptors, fields}};"
        )
        lines.append("")

    lines.extend(
        [
            f"constexpr std::array<const Schema*, {len(schema_names)}> schemas{{{{",
            *(f"  &schema_{name}," for name in schema_names),
            "}};",
            "",
            "}  // namespace",
            "",
            "const TableSchema* Schema::find_table(std::string_view name) const noexcept {",
            "  for (const auto& table : tables) {",
            "    if (table.name == name) {",
            "      return &table;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "std::span<const std::uint8_t> Schema::table_descriptors(",
            "    const TableSchema& table) const noexcept {",
            "  return descriptors.subspan(table.descriptor_offset, table.descriptor_count);",
            "}",
            "",
            "std::span<const FieldSchema> Schema::table_fields(",
            "    const TableSchema& table) const noexcept {",
            "  return fields.subspan(table.field_offset, table.field_count);",
            "}",
            "",
            "const Schema* schema_for(std::string_view internal_format,",
            "                         std::uint8_t database_kind_marker) noexcept {",
            "  for (const Schema* schema : schemas) {",
            "    if (schema->internal_format == internal_format &&",
            "        schema->database_kind_marker == database_kind_marker) {",
            "      return schema;",
            "    }",
            "  }",
            "  return nullptr;",
            "}",
            "",
            "}  // namespace tekla::db1::detail",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("manifests", nargs="+", type=Path)
    args = parser.parse_args()
    manifests = [json.loads(path.read_text()) for path in args.manifests]
    rendered = generate(manifests)
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
